server:
  port: 8081

api:
  V1: v1

spring:
  application:
    name: uamishop-catalogo
  datasource:
    url: jdbc:mysql://localhost:3306/uamishop_catalogo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: uamishop
    password: uamishop
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: catalogo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # Confirmación de que el broker recibió el mensaje
    publisher-confirm-type: correlated
    # El broker avisa si el mensaje llegó al Exchange pero NO pudo enrutarse a ninguna cola
    publisher-returns: true
    template:
      # Obliga al broker a devolver el mensaje si falla el enrutamiento
      mandatory: true

outbox:
  scheduler:
    delay: 5000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
