spring.application.name=uamishop
spring.web.error.include-stacktrace=never
api.V1=v1

# URL del microservicio de catálogo (usado con perfil catalogo-remoto)
catalogo.service.url=http://localhost:8081
# para ordenes
ordenes.service.url=http://localhost:8080
