server:
  port: 8082

api:
  V1: v1

spring:
  application:
    name: uamishop-ordenes

  datasource:
    url: jdbc:mysql://localhost:3306/uamishop_ordenes?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: uamishop
    password: uamishop
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # update: crea/modifica tablas automáticamente sin borrar datos existentes
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Esquema propio del microservicio dentro de la BD uamishop_ordenes
        default_schema: ordenes

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
