server:
  port: 8082

api:
  V1: v1

spring:
  application:
    name: uamishop-ordenes

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/uamishop_ordenes?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:uamishop}
    password: ${SPRING_DATASOURCE_PASSWORD:uamishop}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ordenes

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    # Confirmación de que el broker recibió el mensaje
    publisher-confirm-type: correlated
    # El broker avisa si el mensaje llegó al Exchange pero NO pudo enrutarse a ninguna cola
    publisher-returns: true
    template:
      # Obliga al broker a devolver el mensaje si falla el enrutamiento
      mandatory: true

outbox:
  scheduler:
    delay: 5000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

catalogo:
  service:
    url: ${CATALOGO_SERVICE_URL:http://localhost:8081}

carrito:
  service:
    url: ${CARRITO_SERVICE_URL:http://localhost:8083}

resilience4j:
  circuitbreaker:
    instances:
      catalogoService: # nombre en la anotación
        slidingWindowSize: 5 # evalua las ultimas 5 llamadas
        minimumNumberOfCalls: 3 # minimo de llamadas antes de abrir el CB
        failureRateThreshold: 50 # porcentaje de fallos antes de abrir el CB
        waitDurationInOpenState: 10s # espera 10s antes de pasar a semi abierto
        permittedNumberOfCallsInHalfOpenState: 3 # prueba con 1 llamada
        registerHealthIndicator: true # expone el estado en /actuator/health
      carritoService: # nombre en la anotación
        slidingWindowSize: 5 # evalua las ultimas 5 llamadas
        minimumNumberOfCalls: 3 # minimo de llamadas antes de abrir el CB
        failureRateThreshold: 50 # porcentaje de fallos antes de abrir el CB
        waitDurationInOpenState: 10s # espera 10s antes de pasar a semi abierto
        permittedNumberOfCallsInHalfOpenState: 3 # prueba con 1 llamada
        registerHealthIndicator: true # expone el estado en /actuator/health
